# Generated by Django 4.2.13 on 2024-08-22 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('author', models.CharField(max_length=200, verbose_name='Author')),
                ('translator', models.CharField(blank=True, max_length=200, verbose_name='Translator')),
                ('publisher', models.CharField(max_length=200, verbose_name='Publisher')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('cover', models.ImageField(blank=True, upload_to='covers/', verbose_name='Cover')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is_Active')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime_Created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime_Modified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is-Active')),
                ('recommend', models.BooleanField(default=True, verbose_name='Recommend')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='Datetime_Created')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
