# Generated by Django 4.2.13 on 2024-10-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock'),
        ),
    ]
