# Generated by Django 4.2.13 on 2024-07-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_alter_book_author_alter_book_cover_and_more'),
        ('orders', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='books.book'),
        ),
    ]
